name: testing credentials
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Service Account
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" > service_account.json
          cat service_account.json